site:
  title: Antora Test Docs Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://milojemarkovic.github.io/Antora/
  start_page: antoratest::index.adoc
content:
  sources:
    - url: https://github.com/MilojeMarkovic/Antora.git
      branches: "main"
      start_path: doc

ui:
  bundle:
    url: https://github.com/fabianfnc/bocs/blob/master/doc/uibundle.zip?raw=true
    snapshot: true
