= cadooz Business Order API v1.6.0

:sectnums:
:sectnumlevels: 4
:toc:
:toclevels: 4
:experimental:
:keywords: AsciiDoc
:source-highlighter: highlight.js
:icons: font


Linda Rapp <linda.rapp@cadooz.de>

v1.6.0, December 31, 2022: cadooz Business Order API v1.6.0 Documentation



== Getting Started



=== Step 1

=== API Documentation

Start off by familiarizing yourself with our API documentation.



Integrate the cadooz Business Order API v1.6.0 to automate your orders of vouchers and rewards at cadooz. The SOAP API allowes

you to automate you orders wiht cadooz, choosing from the biggest variaty of gift cards on the german market,

including all of the top brands. This documentation describes the endpoints and provides example requests

as well as example responses, helping you to get started.



=== Step 2

=== API Access

Once you created an API user, using our self-onboarding functionality within the

https://incentivemall.cadooz.com/mall/index.do[Incentive Mall], you can try out the API

calls and start integrating the orders at cadooz as part of your system's workflow.

If you don't have a user for our Incetive Mall yet, you can

https://incentivemall.cadooz.com/mall/register.do[register here].

Once you created your API user you'll receive your login data and can start testing the API right away.



=== Step 3

=== Switch to production

You can manage your API account data within the https://incentivemall.cadooz.com/mall/index.do[Incentive Mall]. That' where you can switch your API access to production,

Once you finished the integration..



== Environments and URLs

=== Test API

* Endpoint https://webservices.cadooztest.de/services/businessorder/1.5.2/BusinessOrderService/BusinessOrder

* WSDL https://webservices.cadooztest.de/services/businessorder/1.5.2/BusinessOrderService/BusinessOrder?wsdl



=== Production API

TIP: If a new production account is creates, it will be a test account till you set it to production.



* Endpoint: https://webservices.cadooz.com/services/businessorder/1.6.0/BusinessOrderService/BusinessOrder

* WSDL: https://webservices.cadooz.com/services/businessorder/1.6.0/BusinessOrderService/BusinessOrder?wsdl



== Authentication

This cadooz businss Order API v1.6.0 uses SOAP v1.1.

All requests must be well-formed, use HTTPS (encrypted) and need an HTTP header authentication.

There are four parts to do

. xref:gettingstarted/setupide.adoc[Setup the IDE]
// . xref:gettingstarted/repository.adoc[Create Repository]
// . xref:gettingstarted/playbook.adoc[Create Playbook Project]
. xref:gettingstarted/githubpages.adoc[Generate and serve it]


== Basic Overview

To build your html docs page with Antora you need a GitHub Repository and a Playbook Project where the docs will be created.

Antora will fetch the necessary files (antora.yml, adoc files ..) out of your Playbook Project and create a html Site out of it.

NOTE: In this Guide we are going to have The Playbook Project inside the Repository for better traceability.

https://pages.github.com/[GitHub Pages icon:external-link[]] will be used to serve our created example docs.

and now .. xref:gettingstarted/setupide.adoc[get started!]

== Useful Links

https://github.com/fabianfnc/bocs[Example Repository + Playbook where we are on icon:external link[]]

https://github.com/OpenEMS/openems/tree/develop/doc[OpenEMS Repository which is also using Antora icon:external link[]]

https://antora.org/[Antora Info Site icon:external link[]]

https://docs.antora.org/antora/1.1/[Antora Docs icon:external link[]]

https://gitlab.com/antora[Antora GitLab Projects icon:external link[]]

http://asciidoc.org/[AsciiDoc Info Site icon:external link[]] 
